//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace exemplu1 {
    using System;
    using System.Collections.Generic;
    
    
    public class Program {
        
        public static System.Collections.Generic.List<string> input;
        
        public static int pozitie;
        
        public static void E() {
            if(input[pozitie] == "a") {
				T();
				E1();
				return;
			}
			if(input[pozitie] == "(") {
				T();
				E1();
				return;
			}
		throw new Exception($"Error at E. Input given: {input[pozitie]}. Expected something else.");
        }
        
        public static void E1() {
            if(input[pozitie] == "+") {
				pozitie++;
				T();
				E1();
				return;
			}
			if(input[pozitie] == ")") {
				return;
			}
			if(input[pozitie] == "$") {
				return;
			}
		throw new Exception($"Error at E1. Input given: {input[pozitie]}. Expected something else.");
        }
        
        public static void T() {
            if(input[pozitie] == "a") {
				F();
				T1();
				return;
			}
			if(input[pozitie] == "(") {
				F();
				T1();
				return;
			}
		throw new Exception($"Error at T. Input given: {input[pozitie]}. Expected something else.");
        }
        
        public static void T1() {
            if(input[pozitie] == "*") {
				pozitie++;
				F();
				T1();
				return;
			}
			if(input[pozitie] == "+") {
				return;
			}
			if(input[pozitie] == ")") {
				return;
			}
			if(input[pozitie] == "$") {
				return;
			}
		throw new Exception($"Error at T1. Input given: {input[pozitie]}. Expected something else.");
        }
        
        public static void F() {
            if(input[pozitie] == "a") {
				pozitie++;
				return;
			}
			if(input[pozitie] == "(") {
				pozitie++;
				E();
				pozitie++;
				return;
			}
		throw new Exception($"Error at F. Input given: {input[pozitie]}. Expected something else.");
        }
        
        public static void Main(string[] args) {
            input = new List<string>(args);
			try
			{
				E();
				if(input[pozitie] == "$")
					Console.WriteLine("Propozitie corecta!");
				else
					Console.WriteLine("Propozitie incorecta!");
			}
			catch(Exception e)
			{
				Console.WriteLine(e.Message);
				Console.WriteLine("Propozitie incorecta!");
			}
			Console.ReadKey();;
        }
    }
}
